# 예외처리

불확실성에 대해 이해하고 대처하기 위한 수업
## 에러와 예외
에러와 예외의 결정적인 차이 : 
프로그래밍을 통해서 대처가 가능한가? 그럴 필요가 있는가? 프로그래머의 관심사 인가? 

- 어떤 원인에 의해 오동작 하거나 비정상적으로 종료되는 경우
- 심각도에 따른 분류
  - Error
    - 메모리 부족, stack overflow 와 같이 일단 발생하면 복구할 수 없는 상황
    - 프로그램의 비 정상적 종료를 막을 수 없음 -> 디버깅 필요
  - Exception
    - 읽으려는 파일이 없거나, 네트워크 연결이 안 되는 등 수습 될 수 있는 비교적 상태가 약한 것들
    - 프로그램 코드에 의해 수습될 수 있는 상황

## 예외처리(Exception Handling)
예외처리 (Exception Handling)란
- 예외 발생 시 프로그램의 비 정상 종료를 막고 정상적인 실행 상태를 유지하는 것
- 예외의 감지 및 예외 발생 시 동작할 코드 작성 필요

1. 주된 관심사와 보조 관심사 분리
  - 메서드의 본래 기능에 집중
  - 보조 관심사는 예외 : 메서드를 사용하는 사람이 처리
2. 미리 발생할 수 있는 문제점을 알려주는 효과 
  - 메서드를 사용하는 사람: 메서드에 throws 발생할 수 있는 예외 처리
3. 메서드를 잘못 사용하는 것을 방지
  
 
## 예외처리(Exception Handling)
예외 클래스의 계층
- Checked exception
  - 예외에 대한 대처 코드가 없으면 컴파일이 진행되지 않음
- Unchecked exception(RuntimeException의 하위 클래스)
  - 예외에 대한 대처 코드가 없더라도 컴파일은 진행됨

## 예외 처리 키워드
- 직접 처리
  - try
  - catch
  - finally
- 간접 처리 (보통은 예외 객체가 발생하는 메서드를 호출하는 메서드)
  - throws (전가)
- 사용자 정의 예외 발생 시킬 때
  - throw 


### try ~ catch 구문
try {
  //예외가 발생할 수 있는 코드
} catch (Exception e) {
  //예외가 발생했을 때 처리할 코드
}


## Exception 객체의 정보 활용
![image](https://user-images.githubusercontent.com/123134689/234190728-c8b44c7d-cdc3-411c-a3ff-4825a3875936.png)


### try ~ catch 문에서의 흐름
- try 블록에서 예외가 발생하면
- JVM이 해당 Exception 클래스의 객체 생성 후 던짐(throw) : throw new XXException()
- 던져진 exception 을 처리할 수 있는 catch 블록에서 받은 후 처리(적당한 catch 블록을 만나지 못하면 예외처리는 실패)
- 정상적으로 처리되면 try-catch 블록을 벗어나 다음 문장 진행
- try 블록에서 어떠한 예외도 발생하지 않는 경우
- catch문을 거치지 않고 try-catch 블록의 다음 흐름 문장을 실행

## 다중 exception handling
- try 블록에서 여러 종류의 예외가 발생할 경우
- 하나의 try 블록에 여러 개의 catch 블록 추가 가능(예외 종류별로 catch 블록 구성)
- 다중 catch 문장 작성 순서 유의 사항
  - JVM이 던진 예외는 catch 문장을 찾을 때는 다형성이 적용됨
  - 상위 타입의 예외가 먼저 선언되는 경우 뒤에 등장하는 catch 블록은 동작할 기회가 없음
  - 상속 관계가 없는 경우는 무관
  - 상속 관계에서는 작은 범위(자식)에서 큰 범위(조상) 순으로 정의
  

![image](https://user-images.githubusercontent.com/123134689/234195207-e77e9cab-6315-4600-aa66-fa130664c92d.png)


### throws 키워드를 통한 처리 위임
- method 에서 처리해야 할 하나 이상의 예외를 호출한 곳으로 전달(처리 위임)
- 예외가 없어지는 것이 아니라 단순히 전달됨
- 예외를 전달받은 메서드는 다시 예외 처리의 책임 발생
- 처리하려는 예외의 조상 타입으로 throws 처리 가능

![image](https://user-images.githubusercontent.com/123134689/234198740-3889a18b-e3a8-4ecd-aa28-94c346429c92.png)

### runtime exception 과 throws
- runtime exception 은 throws 하지 않아도 전달되지만
- 하지만 결국은 try ~ catch로 처리해야 함

## 로그 분석과 예외의 추적
- Throwable 의 printStackTrace 메서드 호출 스택 정보 조회 가능
  - 최초 호출 메서드에서부터 예외 발생 메서드 까지의 스택 정보 출력
- 꼭 확인해야할 정보
  - 어떤 예외인가? : 예외 종류
  - 예외 객체의 메시지는 무엇인가? : 예외 원인
  - 어디서 발생했는가? : 디버깅 출발점
    - 직접 작성한 코드를 디버깅 대상으로 삼을 것
    - 참조하는 라이브러리는 과감히 건너 뛰기

## 메서드 재정의와 throws
- 메서드 재정의 시 조상클래스 메서드가 던지는 예외보다부모 예외를 던질 수 없다.
  
![image](https://user-images.githubusercontent.com/123134689/234201945-0b17b256-558d-4f32-829e-5a906e9521ce.png)

methodB 가 잘못됨  부모보다 더 큰 예외를 던질 수 없다.

# 사용자 정의 예외
- API에 정의돈 exception 이외에 필요에 따라 사용자 정의 예외 클래스 작성
- 대부분 Exception 또는 RuntimeException 클래스를 상속받아 작성
  - checked exception 활용 : 명시적 예외 처리 또는 throws 필요
    (코드는 복잡해지지만 처리, 누락 등 오류 발생 가능성은 down)
  - runtime exception 활용 : 묵시적 예외 처리 가능
    (코드가 간결해지지만 예외 처리, 누락 가능성 발생)
- 사용자 정의 예외를 만들어 처리하는 장점
  - 객체의 활용 : 필요한 추가 정보, 기능 활용 가능
  - 코드의 재사용 : 동일한 상황에서 에외 객체 재사용 가능
  - throws 메커니즘의 이용 : 중간 호출 단계에서 return 불필요